"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var compiller_core_1 = require("../src/compiller/compiller.core");
var TokenTypes_1 = require("../src/core/TokenTypes");
var Token = new Token('1', '2', TokenTypes_1.TokenTypes.INT);
var Token2 = new Token('1', '2', TokenTypes_1.TokenTypes.START);
var TokenList = [];
TokenList.push(Token);
TokenList.push(Token2);
var compiller = new compiller_core_1.default(TokenList);
compiller.__run_compille();
